DROP TABLE IF EXISTS UTILISATEUR;
DROP TABLE IF EXISTS AMITIE;

CREATE TABLE UTILISATEUR(
    id_utilisateur INTEGER PRIMARY KEY AUTOINCREMENT, 
	pseudo_utilisateur varchar(20) UNIQUE,
	bio varchar(150)
);

CREATE TABLE AMITIE(
	util1 varchar(20), 
	util2 varchar(20),
	CONSTRAINT AMITIE PRIMARY KEY (util1,util2),
	CONSTRAINT AMITIE FOREIGN KEY(util1) REFERENCES UTILISATEUR (pseudo_utilisateur)
	CONSTRAINT AMITIE FOREIGN KEY(util2) REFERENCES UTILISATEUR (pseudo_utilisateur)
);