BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "UTILISATEUR" (
	"id_utilisateur"	INTEGER,
	"pseudo_utilisateur"	VARCHAR(20),
	PRIMARY KEY("id_utilisateur" AUTOINCREMENT)
);
INSERT INTO "UTILISATEUR" VALUES (1,'Tom.clv');
INSERT INTO "UTILISATEUR" VALUES (2,'Dorian.jsr');
COMMIT;
